syntax = "proto3";

package account;

option go_package = "github.com/yuliapopova/book_all/contracts/account;account";

service AccountService {
  rpc Deposit (DepositRequest) returns (DepositResponse);
  rpc Withdraw (WithdrawRequest) returns (WithdrawResponse);
  rpc Transfer (TransferRequest) returns (TransferResponse);
  rpc GetBalance (GetBalanceRequest) returns (GetBalanceResponse);
}

message DepositRequest {
  uint64 user_id = 1;
  double amount = 2;
}

message DepositResponse {
  bool success = 1;
  string message = 2;
  uint64 account_id = 3;
  double balance = 4;
}

message WithdrawRequest {
  uint64 account_id = 1;
  double amount = 2;
}

message WithdrawResponse {
  bool success = 1;
  string message = 2;
  double balance = 3;
}

message TransferRequest {
  uint64 account_id = 1;
  uint64 recipient_id = 2;
  double amount = 3;
}

message TransferResponse {
  bool success = 1;
  string message = 2;
  double sender_balance = 3;
  double recipient_balance = 4;
}

message GetBalanceRequest {
  uint64 account_id = 1;
}

message GetBalanceResponse {
  bool success = 1;
  double balance = 2;
}

message AccountResponse {
  string request_type = 1;
  uint64 user_id = 2;
  uint64 operation_id = 3;
  bool result = 4;
}
