syntax = "proto3";

package auth;

option go_package = "github.com/yuliapopova/book_all/contracts/auth;auth";

import "google/protobuf/timestamp.proto";

service AuthService {
  rpc Register (RegisterRequest) returns (RegisterResponse);
  rpc Login (LoginRequest) returns (LoginResponse);
  rpc Logout (LogoutRequest) returns (LogoutResponse);
  rpc Refresh (RefreshRequest) returns (RefreshResponse);
  rpc GetCurrentUser (GetCurrentUserRequest) returns (GetCurrentUserResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  string name = 3;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
  User user = 3;
}

message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  bool success = 1;
  string message = 2;
  string access_token = 3;
  string refresh_token = 4;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  bool success = 1;
  string message = 2;
  string access_token = 3;
  string refresh_token = 4;
}

message GetCurrentUserRequest {
  string access_token = 1;
}

message GetCurrentUserResponse {
  bool success = 1;
  User user = 2;
}

message User {
  uint64 id = 1;
  string email = 2;
  string name = 3;
}
